---
# sed '/swap/d' /etc/fstab
- name: Remove swap partition from /etc/fstab
  mount:
    name: swap
    state: absent

# swapoff -a
- name: Turn off memory swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

# cat <<EOF > /etc/yum.repos.d/kubernetes.repo
# [kubernetes]
# name=Kubernetes
# baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
# enabled=1
# gpgcheck=1
# repo_gpgcheck=1
# gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
# exclude=kube*
# EOF
- name: Add yum repository
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
    - https://packages.cloud.google.com/yum/doc/yum-key.gpg
    - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    # The following line is commented out because Ansible's yum module does
    # not yet support the --disableexcludes option.
    # exclude: kube*

# yum install -y \
#   --disableexcludes kubernetes \
#   kubeadm
- name: Install kubeadm
  yum:
    pkg: kubeadm-1.11.3
